version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # These are tied to the go-libp2p-kad-dht version, so we exclude them.
      - dependency-name: "github.com/libp2p/go-libp2p"
      - dependency-name: "github.com/libp2p/go-libp2p-kbucket"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
